; SPDX-FileCopyrightText: 2026 José Bollo
;
; SPDX-License-Identifier: MIT
; SRFI-266 demo by José Bollo, 2026

(include "expr.scm")


(use-modules
  (language tree-il)
  (srfi srfi-64))

(define (temporary? x)
  (and (symbol? x)
       (let ((s (symbol->string x)))
          (and (>= (string-length s) 2)
               (string=? (substring s 0 2) "t-")))))

(define (rename-temporaries item)
  (define (rt item tmps cont)
    (cond
      ((temporary? item)
        (let ((memo (assoc item tmps)))
          (if memo
            (cont (cdr memo) tmps)
            (let* ((name  (string-append "temporary-"
                                         (number->string (+ 1 (length tmps)))))
                   (symb  (string->symbol name))
                   (memo  (cons item symb)))
              (cont symb (cons memo tmps))))))
      ((pair? item)
        (rt (car item) tmps
            (lambda (item-car tmps)
              (rt (cdr item) tmps
                  (lambda (item-cdr tmps)
                    (cont (if (and (eq? (car item) item-car)
                                   (eq? (cdr item) item-cdr))
                            item
                            (cons item-car item-cdr))
                          tmps))))))
      (else
        (cont item tmps))))
  (rt item '() (lambda (x y) x)))


(test-begin "test expr syntax")
(for-each
  (lambda (x)
    (let* ((e  (car x))
           (r  (cadr x))
           (ex (cons 'expr e))
           (rx (tree-il->scheme (macroexpand ex)))
           (rx (rename-temporaries rx)))
      (when #f
        (display ex)
        (newline)
        (display " => ")
        (display rx)
        (newline))
      (test-equal e r rx)))
  '(
        ((1) 1)
        ((a) a)
        (((a)) a)
        ((((f0))) (f0))
        ((- a) (- a))
        ((- a + b) (+ (- a) b))
        ((+ a) (+ a))
        ((+ - a) (+ (- a)))
        ((? a) (if a 1 0))
        ((a + b) (+ a b))
        ((a + b + c) (+ a b c))
        ((a - b) (- a b))
        ((a - b - c) (- a b c))
        ((a + b - c - d - e + 4 + 5 * f) (+ (- (+ a b) c d e) 4 (* 5 f)))
        ((a / b) (/ a b))
        ((a / b / c) (/ a b c))
        ((a * b) (* a b))
        ((a * b * c) (* a b c))
	((- a ** (i + j)) (- (expt a (+ i j))))
	((- a * (i + j)) (* (- a) (+ i j)))
        ((a + b * c * d) (+ a (* b c d)))
        ((a * b + c * d) (+ (* a b) (* c d)))
        ((a \ b) (quotient a b))
        ((a \ b \ c) (quotient (quotient a b) c))
        ((a % b) (remainder a b))
        ((a % b % c) (remainder (remainder a b) c))
        ((1 << a % 8) (arithmetic-shift 1 (remainder a 8)))
        ((65536 >> a % 8) (arithmetic-shift 65536 (- (remainder a 8))))
        ((f1 a) (f1 a))
        ((f1 a + b) (+ (f1 a) b))
        ((f1 a * b) (f1 (* a b)))
        ((f1 (a + b)) (f1 (+ a b)))
        ((f3 (a b + c d)) (f3 a (+ b c) d))
        ((f2 ((a + b) c)) (f2 (+ a b) c))
        ((f1 g1 a) (f1 (g1 a)))
        (((ff g1) a) ((ff g1) a))
        ((ff1 (g a)) (ff1 g a))
        ((cos 2 * a + sin 3 * b) (+ (cos (* 2 a)) (sin (* 3 b))))
        ((square cos a + square sin b) (+ (square (cos a)) (square (sin b))))
        ((a < b < c) (< a b c))
        ((a < b <= c) (let ((temporary-1 b)) (and (< a temporary-1) (<= temporary-1 c))))
        ((a < b <= c < d) (let ((temporary-1 b)) (and (< a temporary-1) (let ((temporary-2 c)) (and (<= temporary-1 temporary-2) (< temporary-2 d))))))
        ((a = b = c < d < e) (let ((temporary-1 c)) (and (= a b temporary-1) (< temporary-1 d e))))
        ((@ B != 78) (not (= (unbox B) 78)))
        ((u implies z) (or (not u) z))
        ((a and b and c or u or v and not i) (or (and a b c) u (and v (not i))))
        (((a and b and c) or u or (v and not i)) (or (and a b c) u (and v (not i))))
        ((a and b and (c or u or v) and not i) (and a b (or c u v) (not i)))
        ((45 if a else 28) (if a 45 28))
        ((a + b if x implies y else 7 * b + a) (if (or (not x) y) (+ a b) (+ (* 7 b) a)))
        ((a if (b if c else d) else e) (if (if c b d) a e))
        ((a if b if c else d else e) (if (if c b d) a e))
        ((a + b as c in c * d) (let-values (((c) (+ a b))) (* c d)))
        ((a + b as v in 4 * v ** 2 + 5 * v + 34) (let-values (((v) (+ a b))) (+ (* 4 (expt v 2)) (* 5 v) 34)))
        ((a + b as v in 4 * v ** 2 + 5 * v - 34) (let-values (((v) (+ a b))) (- (+ (* 4 (expt v 2)) (* 5 v)) 34)))
        ((a + b as v in 4 * v ** 2 - 5 * v + 34) (let-values (((v) (+ a b))) (+ (- (* 4 (expt v 2)) (* 5 v)) 34)))
        ((floor/ (a b) as q r in q + ? positive? r) (let-values (((q r) (floor/ a b))) (+ q (if (positive? r) 1 0))))
        ((a if (b if (u as v in w) else d) else e) (if (if (let-values (((v) u)) w) b d) a e))
        ((a if b if u as v in w else d else e) (if (if (let-values (((v) u)) w) b d) a e))
   ))

(test-end "test expr syntax")

(test-begin "test lambda-expr syntax")
(test-equal 'lambda-expr '(2 5 10) (map (lambda-expr (x) x * x + 1) '(1 2 3)))
(define-expr (next x) x + 1)
(test-equal 'define-expr '(2 5 10) (map next '(1 4 9)))
(test-begin "test lambda-expr syntax")

